- label: wisdom1
  title: "AI & wisdom 1: wisdom, amortised optimisation, and AI"
  date: 2024-10-12
  description: A lot of wisdom is about mental qualities shaped more by amortised optimisation than direct optimisation. Direct optimisation is solving problems by searching through alternatives on the fly, while amortised optimisation is solving a problem by applying past data and computation. LLMs are products of amortised optimisation, but can be used for direct optimisation.
  math: true
  type: ["general"]
  tags: ["civilisation"]
  sequel: wisdom2


- label: wisdom2
  title: "AI & wisdom 2: growth and amortised optimisation"
  date: 2024-10-13
  description: Amortised optimisation matters more when growth and change are slow, so the relative importance of it will likely decline with the growth and changed caused by AI. However, a model suggests it's hard for amortised optimisation to entirely decline in relevance.
  math: true
  type: ["general"]
  tags: ["civilisation"]
  sequel: wisdom3
  prequel: wisdom1


- label: wisdom3
  title: "AI & wisdom 3: AI effects on amortised optimisation"
  date: 2024-10-14
  description: Human amortised optimisation is enabled by things like cultural evolution and written knowledge. Advanced AI may weaken human cultural evolution, but may themselves be very good at it due to their low copying costs. AIs might help humans distil insights from written knowledge, but ultimately replace the need for it.
  math: true
  type: ["general"]
  tags: ["civilisation", "AI"]
  prequel: wisdom2

- label: infotheory1
  title: Information Theory 1
  date: 2022-06-20
  description: Notes on what information and entropy are (both intuitively and axiomatically) , basic concepts and results in information theory (mutual information, relative entropy AKA KL divergence, the data processing inequality, etc.), and what the point of source and channel coding is.
  math: true
  type: ["technical"]
  tags: ["maths"]
  sequel: "infotheory2"
  prequel: "infotheory1"

- label: infotheory2
  title: Information Theory 2
  date: 2022-06-25
  description: Notes on source coding, a big branch of information theory that deals with compressing information, including an overview of Huffman, arithmetic, and Lempel-Ziv coding, and a proof of the source coding theorem.
  math: true
  type: ["technical"]
  tags: ["maths"]
  prequel: "infotheory1"

- label: infotheory3
  title: "Information Theory 3"
  date: 2022-06-25
  description: "Notes on channel coding, a big branch of information theory that deals with storing information in error-resistant ways, including an overview of Hamming codes, and a proof of the channel coding theorem."
  math: true
  type: ["technical"]
  tags: ["maths"]
  prequel: "infotheory2"

- label: sicp
  title: "Review: Structure and Interpretation of Computer Programs"
  date: 2019-09-08
  description: "The legendary programming book."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["computing"]

- label: doomsday-machine
  title: "Review: The Doomsday Machine"
  date: 2020-04-23
  description: "An overview of the threats posed by nuclear war, including first-hand accounts of American nuclear war planning during the Cold War."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["history"]

- label: where-is-my-flying-car
  title: "Review: Where is my Flying Car?"
  date: 2021-03-21
  description: "An argument that flying cars are actually practical and feasible, and more generally that technological progress has been slowed by regulation and modern culture. Includes lots of cool tech speculation."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["civilisation"]

- label: internationalists
  title: "Review: The Internationalists"
  date: 2018-06-15
  description: "A legal perspective on the decline of war."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["history"]

- label: godel-escher-bach
  title: "Review: Gödel, Escher, Bach"
  date: 2018-04-22
  description: "An extremely clever exploration of ideas about math and cognition."
  math: true
  type: ["book reviews", "nonfiction"]
  tags: ["computing"]

- label: short-reviews-biographies-1
  title: "Short reviews - biographies - 1"
  date: 2021-09-30
  description: "Notes on three of Walter Isaacson's biographies."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["history"]

- label: pleasures-of-counting
  title: "Review: The Pleasures of Counting"
  date: 2019-08-20
  description: "A broad, enjoyable, and quirky exploration of the uses of mathematics."
  math: true
  type: ["book reviews", "nonfiction"]
  tags: ["computing"]

- label: seeds-of-science
  title: "Review: Seeds of Science"
  date: 2018-12-30
  description: "Why are genetically modified crops so reviled, despite the scientific consensus that they're safe?"
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["civilisation"]

- label: foragers-farmers-fossil-fuels
  title: "Review: Foragers, Farmers, and Fossil Fuels"
  date: 2020-12-17
  description: "How much can the way in which civilisations capture energy shape the values that they adopt?"
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["civilisation", "history"]

- label: nand-to-tetris
  title: "Review: From NAND To Tetris"
  date: 2019-08-15
  description: "A fast-paced, concise, yet comprehensive journey from logic gates and DFFs all the way to the implementation of operating systems and high-level programming languages."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["computing"]

- label: enlightenment-now
  title: "Review: Enlightenment Now"
  date: 2018-08-29
  description: "A timely reminder that, contrary to the impression generated by constant negative news, not everything is going to hell and many global trends are actually very positive."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["civilisation"]

- label: amusing-ourselves-to-death
  title: "Review: Amusing Ourselves to Death"
  date: 2019-08-01
  description: "How did television affect public discourse, and what does this tell us about new mediums like the internet?"
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["civilisation"]

- label: energy-and-civilization
  title: "Review: Energy and Civilization: A History"
  date: 2018-10-28
  description: "An information-dense book about historical energy use that lives up to its ambitious title."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["history", "civilisation"]
  sequel: energy-and-civilization-more

- label: energy-and-civilization-more
  title: "Review addendum: More energy and more civilization"
  date: 2018-10-29
  description: "More thoughts on Energy and Civilization: A History."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["history", "civilisation"]
  prequel: "energy-and-civilization"

- label: short-reviews-nonfiction-1
  title: "Short reviews: nonfiction (1)"
  date: 2020-05-09
  description: "Brief notes on various nonfiction books."
  math: false
  type: ["book reviews", "nonfiction"]
  tags: ["computing", "history", "physics"]
  sublist: 
    - "Security Engineering"
    - "Origin Story: A Big History of Everything"
    - "The Character of Physical Law"
    - "The Feynman Lectures on Physics"
    - "Founders at Work"
    - "The Great Leveler: Violence and the History of Inequality"
    - "The Strategy of Conflict"

- label: diaspora
  title: "Review: Diaspora"
  date: 2019-05-30
  description: "A wild and very well thought-out ride through a far-future world, featuring fictional physics theories plausible enough that they may one day win a Nobel."
  math: false
  type: ["book reviews", "fiction"]
  tags: ["physics"]

- label: permutation-city
  title: "Review: Permutation City"
  date: 2018-05-21
  description: "This book is mostly a sustained thought experiment that extrapolates crazy but internally consistent conclusions from its philosophical premises."
  math: false
  type: ["book reviews", "fiction"]
  tags: ["computing"]

- label: baroque-cycle
  title: "Review: The Baroque Cycle"
  date: 2018-06-28
  description: "An expansive story about science, finance, politics, and alchemy in the late 1600s and early 1700s. Almost every natural philosopher of the time makes an appearance, with Newton, Leibniz, and Hooke each being significant characters."
  math: false
  type: ["book reviews", "fiction"]
  tags: ["history"]

- label: short-reviews-fiction-1
  title: "Short reviews: fiction (1)"
  date: 2020-05-09
  description: "Brief notes on various fiction books."
  math: false
  type: ["book reviews", "fiction"]
  tags: ["computing"]
  sublist:
    - "Unsong"
    - "The Curse of Chalion"
    - "Exhalation"
    - "Summerland"
    - "Cryptonomicon"

- label: growth-and-civilisation
  title: "Growth and civilisation"
  date: 2019-09-27
  description: "A constantly expanding economy is one reason why societal norms and moral values have shifted for the better. If growth ceases, a reversion from norms of value-creation and tolerance back to norms of capturing value from others and defending your own in-group is possible in the long run."
  math: false
  type: ["general"]
  tags: ["civilisation"]

- label: ea-rigour-and-opportunity-in-charity
  title: "EA ideas 1: rigour and opportunity in charity"
  date: 2020-07-24
  description: "Effective altruism is about carefully reasoning how to do the most good. A focus on impartial welfarist good, the effectiveness of our efforts, and open-minded uncertainty-acknowledging reasoning leads to a different picture of charity than the usual, but also one that is more likely to do good."
  math: false
  type: ["general"]
  tags: ["EA"]
  sequel: "ev-and-risk-neutrality"

- label: ev-and-risk-neutrality
  title: "EA ideas 2: expected value and risk neutrality"
  date: 2020-07-25
  description: "A rational agent maximises the expected value of what it cares about. Expected value reasoning is not free of problems, but, outside extreme thought experiments and applied carefully, it clears most of them, including 'Pascal's mugging' (high-stakes, low-probability situations). Expected value reasoning implies risk neutrality. The most effective charity may often be a risky one, and gains from giving may be dominated by a few risky bets."
  math: true
  type: ["general"]
  tags: ["EA"]
  sequel: "ea-uncertainty"
  prequel: "ea-rigour-and-opportunity-in-charity"

- label: ea-uncertainty
  title: "EA ideas 3: uncertainty"
  date: 2020-07-26
  description: "We are uncertain about both what is right and what is true (being mindful of the difference is often important). Moral uncertainty raises the question of how we should act when we have credence in more than one moral theory. Uncertainty about truth has many sources, including ones broader than uncertainty about specific facts, such as our biases or the difficulty of confirming some facts. These uncertainties suggest we are unaware of huge problems and opportunities."
  math: false
  type: ["general"]
  tags: ["EA"]
  sequel: "utilitarianism"
  prequel: "ev-and-risk-neutrality"

- label: utilitarianism
  title: "EA ideas 4: utilitarianism"
  date: 2020-08-10
  description: "While not a necessary part of EA thinking, utilitarianism is the most successful description of the core of human ethics so far. In principle (if not practice, due to the complexity of defining utility), it is capable of deciding every moral question, an important property for a moral system. Our moral progress over the past few centuries can be summarised as a transition to more utilitarian morality."
  math: false
  type: ["general"]
  tags: ["EA"]
  prequel: "ea-uncertainty"

- label: technological-progress
  title: "Technological progress"
  date: 2021-03-25
  description: "There are several reasons to think that it's easy to care too little about technological progress. There are many ways we can try to model what technological progress should be like, and hard to figure out which model is right. Which model is right impacts the question of whether technological progress is stagnating, which is also a confusing question. Despite all this confusion, to bring about a good future probably requires that our civilisation gets a lot better at making choices about technology."
  math: false
  type: ["general"]
  tags: ["civilisation"]

- label: nuclear-power
  title: "Nuclear power is good"
  date: 2021-03-27
  description: "Nuclear power is seen as dangerous and unclean. In fact, statistics reveal it is equal to wind and solar in both safety and environmental impact, while the health and environmental impacts of fossil fuels (in particular coal) are massive; as bad in lost human life as a Chernobyl a week, and a significant driver of climate change. We should build more nuclear power as fast as we can."
  math: false
  type: ["general"]
  tags: ["civilisation"]

- label: death-is-bad
  title: "Death is bad"
  date: 2021-10-17
  description: "Surprisingly many people have arguments against making people immortal, ranging from environmentalism to effects on social progress to equality. I argue that technology that can remove the mandatory death sentence that everyone is born with would be good."
  math: false
  type: ["general"]
  tags: ["civilisation"]

- label: ea-in-practice
  title: "Effective Altruism in practice"
  date: 2022-08-20
  description: "EA ideas are discussed in a previous post series, but what does the EA movement/community/whatever actually look like in practice, where did it come from, and whose idea was it to give those philosophy nerds all that money?"
  math: false
  type: ["general"]
  tags: ["EA"]

- label: ea-schelling-point
  title: "EA as a Schelling point"
  date: 2022-09-10
  description: "A significant way in which the Effective Altruism community creates value is by acting as a 'focal' or 'Schelling point' where talented, ambitious, and altruistic people tend to gather and can meet each other. It might be useful to think about what optimising for being a Schelling point looks like, and I list some vague thoughts on that."
  math: false
  type: ["general"]
  tags: ["EA"]

- label: ai-risk-intro-1
  title: "AI risk intro 1: advanced AI might be very bad"
  date: 2022-09-11
  description: "The most likely way for human civilisation to be destroyed this century is through advanced AI systems, and in particular misaligned AI systems (rather than just humans using advanced AI for bad ends). This post is meant as an accessible introduction to the arguments."
  math: false
  type: ["general"]
  tags: ["AI"]
  coauthors: ["Callum McDougall"]

- label: ai-risk-intro-2
  title: "AI risk intro 2: solving the problem"
  date: 2022-09-24
  description: "The field of AI alignment is growing but does not yet have a central paradigm. This post surveys the types of work that people are concretely doing to try to reduce risks from advanced AI systems. If you're confused about what this work actually looks like, this post is for you, regardless of your background."
  math: false
  type: ["general"]
  tags: ["AI"]
  coauthors: ["Callum McDougall"]

- label: research-skill-model
  title: "A model of research skill"
  date: 2024-01-08
  description: "Doing research means answering questions no one yet knows the answer to. This post tries to find and describe the core parts of being good at this"
  math: false
  type: ["general"]
  tags: ["civilisation"]

- label: positive-visions-for-ai
  title: "Positive visions for AI"
  date: 2024-07-23
  description: "Advanced AI draws nearer, but discussions of how it might go well are strangely lacking. In this post, we try to sketch out some general ways in which successful integration of AI might be very good for society."
  math: false
  type: ["general"]
  tags: ["AI"]
  coauthors: ["Florence Hinder"]

- label: human-data-for-alignment
  title: "Deciding not to found a human-data-for-alignment startup"
  date: 2022-09-27
  description: "Matt Putz and I worked together for the first half of summer 2022 to figure out if we should found a startup with the purpose of helping AI alignment researchers get the datasets they need to train their ML models. This post is a summary of our findings, and why we decided to not do it."
  math: false
  type: ["project reports"]
  tags: ["AI"]
  coauthors: ["Matt Putz"]

- label: ai-insurance
  title: "Investigating an insurance-for-AI startup"
  date: 2024-09-21
  description: "Flo Hinder and I worked together for a month during summer 2024 to figure out if we should found an insurance startup to mitigate AI risk. We chose not to, but we think someone else should."
  math: false
  type: ["project reports"]
  tags: ["AI"]
  coauthors: ["Florence Hinder"]

- label: two-proofs
  title: "Two proofs"
  date: 2019-06-29
  description: "Two accessible, visual, and (dare I say it?) fun proofs of simple mathematical results."
  math: true
  type: ["technical"]
  tags: ["computing"]

- label: classical-physics
  title: "Classical physics"
  date: 2019-12-30
  description: "A summary of the form, gist, and 'character' of all fundamental laws of classical physics."
  math: true
  type: ["technical"]
  tags: ["physics"]

- label: data-science-1
  title: "Data science 1"
  date: 2020-12-31
  description: "Notes on fundamental data science concepts (notation; some probability laws; maximum likelihood estimation; supervised and unsupervised learning; fitting, interpreting, and visualising linear models; empirical distributions; KL divergence)."
  math: true
  type: ["technical"]
  tags: ["computing"]

- label: data-science-2
  title: "Data science 2"
  date: 2021-01-22
  description: "More data science notes (Monte Carlo methods; Bayesianism and frequentism; randomised computational methods for Bayesian and frequentist calculations; Markov's, Chebyshev's, and Jensen's inequalities; causal diagrams; Markov chains)."
  math: true
  type: ["technical"]
  tags: ["computing"]

- label: lambda-calculus
  title: "Lambda calculus"
  date: 2021-04-25
  description: "The lambda calculus is a simple model of computation (like Turing machines). This post introduces it, shows how to do useful things in it, and works up to a lambda calculus interpreter written in lambda calculus."
  math: true
  type: ["technical"]
  tags: ["computing"]

- label: disneyland-without-children
  title: "A Disneyland Without Children"
  date: 2023-06-04
  description: "A short story."
  math: false
  type: ["fiction"]
  tags: ["civilisation"]

- label: powerful-proof-techniques
  title: "Powerful proof techniques"
  date: 2018-09-06
  description: "The summary of this post is left as an exercise for the reader."
  math: true
  type: ["humour"]
  tags: ["maths"]

- label: ultimate-literary-essay
  title: "The Ultimate Literary Essay"
  date: 2019-06-26
  description: "The academic literary essay that I've always wanted to write."
  math: false
  type: ["humour"]
  tags: ["satire"]